name: archive

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  archive:
    name: archive files
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.email "lwh8762@gmail.com"
          git config --global user.name "lewohy"

      - name: Checkout to archive
        run: |
          git checkout -b archive

      - name: Remove all files
        run: |
          git rm -r --cached .
        
      - name: Create .txt file
        run: echo "${{ github.server_url }}/${{ github.repository }}" > ./github.txt

      - name: Add files
        run: |
          git add *.py *.txt
          git commit -m "Update archive branch with selected files"

      - name: Push changes
        run: |
          git push origin archive --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
